from pydantic import BaseModel, Field
from typing import Dict, Any


class AgentPlanRequest(BaseModel):
    prompt: str = Field(..., description="The natural language planning request from the user.")


class AgentPlanResponse(BaseModel):
    intent: Dict[str, Any] = Field(..., description="Structured intent parsed from the user prompt.")
    deterministic_metrics: Dict[str, Any] = Field(..., description="Raw metrics generated by deterministic engines.")
    interpretations: Dict[str, str] = Field(..., description="Specialized agent interpretations of metrics.")
    validation: Dict[str, Any] = Field(..., description="Critic validation status and safety checks.")
    report: str = Field(..., description="Synthesized Markdown executive report.")
